import manifest from './assets/fixture-manifest.json';
import smallModelUrl from './assets/MF-MODEL-SMALL.glb?url';
import fallbackImageUrl from './assets/mf-pump-fallback.png';

/** Fixture facts generated by testing/fixtures/models/generate-models.mjs (do not edit by hand). */
export interface ModelFixture {
  id: string;
  bytes: number;
  sha256: string;
  triangles: number;
  vertices: number;
  meshes: number;
  materials: number;
  textureCount: number;
  textureResolutions: string[];
  parts: { name: string; partId: string; label: string }[];
}

export const MODEL_FIXTURES: ModelFixture[] = manifest.models;

export function fixtureById(id: string): ModelFixture | undefined {
  return MODEL_FIXTURES.find(m => m.id === id);
}

export function fixtureBySha(sha: string | null): ModelFixture | undefined {
  return sha ? MODEL_FIXTURES.find(m => m.sha256 === sha) : undefined;
}

export const FALLBACK = { url: fallbackImageUrl, alt: manifest.fallback.alt, sha256: manifest.fallback.sha256, width: manifest.fallback.width, height: manifest.fallback.height };

export const SMALL_MODEL_URL = smallModelUrl;

/** Sibling of the bundled model that is never emitted: the missing-asset control (MF-MODEL-MISSING). */
export function missingModelUrl(): string {
  return new URL('MF-MODEL-MISSING.glb', new URL(smallModelUrl, document.baseURI)).href;
}
