#!/usr/bin/env python3
"""Build testing/test-plan-index.json from a dated Jira snapshot.

The index maps every SMF story to its acceptance-test case IDs and quotes each case's
specification verbatim from the snapshot. It contains specifications only, never results.

Usage: python3 scripts/build-test-plan-index.py [--snapshot docs/jira-snapshot/<date>] [--check]
  --check  exit 1 if the committed index differs from what the snapshot produces.
"""
import argparse, json, re, sys
from pathlib import Path, PurePath

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "testing" / "test-plan-index.json"
INDEX_VERSION = "1.1.0"
TABLE = ROOT / "testing" / "README.md"

CASE_RE = re.compile(r"^\* ([A-Z0-9]+-\d{2}): (.+)$", re.M)
PERSONA_RE = re.compile(r"\b(?:MF-)?(ADMIN|TECH|SUPPORT|RESTRICTED)\b")
FIXTURE_RE = re.compile(r"\bMF-(?!ADMIN\b|TECH\b|SUPPORT\b|RESTRICTED\b)[A-Z]+(?:-[A-Z0-9]+)*\b")


def refs(text: str) -> dict:
    """Logical persona/fixture IDs mentioned in text (short persona names normalised to MF-*)."""
    personas = sorted({f"MF-{m}" for m in PERSONA_RE.findall(text)})
    fixtures = sorted(set(FIXTURE_RE.findall(text)))
    return {"persona_refs": personas, "fixture_refs": fixtures}


def field(body: str, label: str) -> str:
    m = re.search(rf"^\*\*{re.escape(label)}:\*\* (.+)$", body, re.M)
    return m.group(1).strip() if m else ""


def rel_posix(p, root=ROOT) -> str:
    """Repository-relative path with "/" separators on every OS (index and Markdown links)."""
    p = p if isinstance(p, PurePath) else Path(p)
    return p.relative_to(root).as_posix()


def latest_snapshot() -> Path:
    snaps = sorted(p for p in (ROOT / "docs" / "jira-snapshot").iterdir() if p.is_dir())
    return snaps[-1]


def parse_story(path: Path) -> dict:
    text = path.read_text(encoding="utf-8").replace("\r\n", "\n")
    front, body = text.split("\n---\n", 1)
    meta = {}
    for line in front.strip("-\n").splitlines():
        k, v = line.split(":", 1)
        meta[k.strip()] = v.strip()
    summary = json.loads(meta["summary"])
    order = re.search(r"\*\*Backlog order:\*\* (\d+) of \d+ · \*\*Track:\*\* (.+?) · \*\*Reference:\*\* (\S+)", body)
    deps_line = re.search(r"^\*\*Dependencies:\*\*(.*)$", body, re.M)
    deps = sorted(set(re.findall(r"\[(SMF-\d+)\]", deps_line.group(1))), key=lambda k: int(k[4:])) if deps_line else []
    checklist = re.search(r"\*\*Acceptance test checklist[^\n]*\*\*\n\n(.*?)\n\n", body, re.S)
    cases = [{"id": cid, "spec": spec.strip(), **refs(spec)}
             for cid, spec in CASE_RE.findall(checklist.group(1) if checklist else "")]
    test_users = field(body, "Test users / actors")
    test_data = field(body, "Test data / prerequisites")
    evidence = re.search(r"^\*\*Required evidence and completion:\*\* (.+?)\n\n(Record case ID[^\n]+)", body, re.M | re.S)
    story_refs = refs(" ".join([test_users, test_data] + [c["spec"] for c in cases]))
    return {
        "key": meta["key"],
        "summary": summary,
        "url": meta["url"],
        "backlog_order": int(order.group(1)) if order else None,
        "track": order.group(2) if order else None,
        "reference": order.group(3) if order else None,
        "dependencies": deps,
        "snapshot": rel_posix(path),
        "test_users": test_users,
        "test_data": test_data,
        **story_refs,
        "required_evidence": {
            "completion": evidence.group(1).strip() if evidence else "",
            "record": evidence.group(2).strip() if evidence else "",
            "fields": "testing/contract.json#evidence_fields",
            "template": "evidence/TEMPLATE.md",
        },
        "cases": cases,
    }


def build(snapshot: Path) -> dict:
    stories = [parse_story(p) for p in snapshot.glob("SMF-*.md")]
    stories.sort(key=lambda s: int(s["key"].split("-")[1]))
    return {
        "index_version": INDEX_VERSION,
        "source": "Jira project SMF (answersllc.atlassian.net); Jira descriptions are authoritative",
        "retrieved": snapshot.name,
        "snapshot_dir": rel_posix(snapshot),
        "note": "Specifications only. No execution results are recorded here; see evidence/. "
                "test_users, test_data, case spec (expected outcome) and required_evidence are quoted verbatim "
                "from the snapshot; persona_refs/fixture_refs are extracted logical IDs defined in testing/contract.json. "
                "Personas and fixtures are specifications, not proof that accounts or data exist.",
        "story_count": len(stories),
        "case_count": sum(len(s["cases"]) for s in stories),
        "stories": stories,
    }


def render_markdown(idx: dict) -> str:
    lines = [
        "# Test-plan index",
        "",
        f"<!-- Generated by scripts/build-test-plan-index.py from {idx['snapshot_dir']}. Do not edit by hand. -->",
        "",
        f"Index version {idx['index_version']} · retrieved {idx['retrieved']} · "
        f"{idx['story_count']} stories · {idx['case_count']} case IDs. "
        "Jira descriptions are authoritative; this is a navigation aid containing **specifications only**.",
        "",
        "Shared personas, fixtures, environments, evidence fields and Definition of Done: "
        "[`contract.json`](contract.json) (from SMF-3). Results go in [`../evidence/`](../evidence/).",
        "",
        "| Story | Order · Track | Depends on | Case IDs | Personas | Fixtures |",
        "|---|---|---|---|---|---|",
    ]
    for s in idx["stories"]:
        deps = ", ".join(s["dependencies"]) or "—"
        ids = ", ".join(c["id"] for c in s["cases"])
        pers = ", ".join(s["persona_refs"]) or "—"
        fix = ", ".join(s["fixture_refs"]) or "—"
        lines.append(f"| [{s['key']}]({s['url']}) {s['summary']} | {s['backlog_order']} · {s['track']} | {deps} | {ids} | {pers} | {fix} |")
    lines += ["", "## Case specifications", ""]
    for s in idx["stories"]:
        lines.append(f"### {s['key']} — [{s['snapshot'].split('/')[-1]}](../{s['snapshot']})")
        lines.append("")
        lines.append(f"- *Test users / actors:* {s['test_users']}")
        lines.append(f"- *Test data / prerequisites:* {s['test_data']}")
        lines.append("")
        for c in s["cases"]:
            lines.append(f"- **{c['id']}**: {c['spec']}")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--snapshot", type=Path)
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    snapshot = (ROOT / a.snapshot) if a.snapshot else latest_snapshot()
    idx = build(snapshot)
    out = json.dumps(idx, indent=2, ensure_ascii=False) + "\n"
    md = render_markdown(idx)
    if a.check:
        stale = [p for p, want in ((INDEX, out), (TABLE, md)) if not p.exists() or p.read_text(encoding="utf-8").replace("\r\n", "\n") != want]
        if stale:
            print(f"FAIL: {', '.join(str(p.relative_to(ROOT)) for p in stale)} out of date with {snapshot.relative_to(ROOT)}; rebuild.")
            return 1
        print(f"OK: index matches {snapshot.relative_to(ROOT)}")
        return 0
    INDEX.write_text(out, encoding="utf-8", newline="\n")
    TABLE.write_text(md, encoding="utf-8", newline="\n")
    print(f"wrote {INDEX.relative_to(ROOT)} and {TABLE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
