#!/usr/bin/env python3
"""Generate the SMF-3 local file fixtures deterministically (DATA-04). Standard library only.

  python3 testing/fixtures/generate.py           # (re)write every fixture, then verify
  python3 testing/fixtures/generate.py --check   # verify files/hashes against manifest.json

Fixtures (logical IDs from testing/contract.json):
  MF-IMAGE-001       synthetic pump schematic PNG (<= 2 MiB), linked to MF-CASE-001 by the seed
  MF-FILE-DENIED     a different synthetic image, linked only to MF-CASE-002 by the seed
  MF-UPLOAD-INVALID  a .txt file and a > 5 MiB PNG for the image-only 5 MiB upload limit

Every image is drawn procedurally: no people, no customer data, no camera/EXIF/GPS metadata
(PNG chunks are IHDR, PLTE, tEXt Comment, IDAT, IEND only). Output is byte-identical on every
platform because the deflate stream uses stored blocks written here, not the zlib library's
compressor (whose output differs between zlib versions). Licence: generated by this
repository, dedicated to the public domain under CC0-1.0.

The > 5 MiB image is not committed (testing/fixtures/.gitignore); its size and SHA-256 are in
manifest.json, and this script regenerates the identical bytes.
"""
import argparse, hashlib, json, struct, sys, zlib
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
MANIFEST = HERE / "manifest.json"
MIB = 1024 * 1024
LICENCE = "CC0-1.0 (generated by this repository: testing/fixtures/generate.py)"
GENERATOR = "testing/fixtures/generate.py"

# ---------------------------------------------------------------- PNG writer (deterministic)

def _chunk(kind, data):
    return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF)


def _stored_zlib(raw):
    """zlib stream with stored (uncompressed) deflate blocks: identical bytes everywhere."""
    out = bytearray(b"\x78\x01")
    n = len(raw)
    pos = 0
    while True:
        block = raw[pos:pos + 65535]
        pos += len(block)
        final = 1 if pos >= n else 0
        out += bytes([final]) + struct.pack("<HH", len(block), len(block) ^ 0xFFFF) + block
        if final:
            break
    out += struct.pack(">I", zlib.adler32(raw) & 0xFFFFFFFF)
    return bytes(out)


def png_indexed(width, height, rows, palette, comment):
    """rows: list of bytes (palette indices, one byte per pixel)."""
    raw = b"".join(b"\x00" + r for r in rows)
    plte = b"".join(bytes(c) for c in palette)
    return (b"\x89PNG\r\n\x1a\n"
            + _chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 3, 0, 0, 0))
            + _chunk(b"PLTE", plte)
            + _chunk(b"tEXt", b"Comment\x00" + comment.encode("latin-1"))
            + _chunk(b"IDAT", _stored_zlib(raw))
            + _chunk(b"IEND", b""))


def png_rgb(width, height, raw_rows, comment):
    raw = b"".join(b"\x00" + r for r in raw_rows)
    return (b"\x89PNG\r\n\x1a\n"
            + _chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0))
            + _chunk(b"tEXt", b"Comment\x00" + comment.encode("latin-1"))
            + _chunk(b"IDAT", _stored_zlib(raw))
            + _chunk(b"IEND", b""))

# ---------------------------------------------------------------- tiny raster canvas

FONT = {  # 5x7 bitmap glyphs, one string per row
    "A": ["01110", "10001", "10001", "11111", "10001", "10001", "10001"],
    "C": ["01111", "10000", "10000", "10000", "10000", "10000", "01111"],
    "D": ["11110", "10001", "10001", "10001", "10001", "10001", "11110"],
    "E": ["11111", "10000", "10000", "11110", "10000", "10000", "11111"],
    "F": ["11111", "10000", "10000", "11110", "10000", "10000", "10000"],
    "H": ["10001", "10001", "10001", "11111", "10001", "10001", "10001"],
    "I": ["11111", "00100", "00100", "00100", "00100", "00100", "11111"],
    "L": ["10000", "10000", "10000", "10000", "10000", "10000", "11111"],
    "M": ["10001", "11011", "10101", "10101", "10001", "10001", "10001"],
    "N": ["10001", "11001", "10101", "10011", "10001", "10001", "10001"],
    "O": ["01110", "10001", "10001", "10001", "10001", "10001", "01110"],
    "P": ["11110", "10001", "10001", "11110", "10000", "10000", "10000"],
    "R": ["11110", "10001", "10001", "11110", "10100", "10010", "10001"],
    "S": ["01111", "10000", "10000", "01110", "00001", "00001", "11110"],
    "T": ["11111", "00100", "00100", "00100", "00100", "00100", "00100"],
    "U": ["10001", "10001", "10001", "10001", "10001", "10001", "01110"],
    "V": ["10001", "10001", "10001", "10001", "10001", "01010", "00100"],
    "Y": ["10001", "10001", "01010", "00100", "00100", "00100", "00100"],
    "0": ["01110", "10001", "10011", "10101", "11001", "10001", "01110"],
    "1": ["00100", "01100", "00100", "00100", "00100", "00100", "01110"],
    "2": ["01110", "10001", "00001", "00010", "00100", "01000", "11111"],
    "3": ["11110", "00001", "00001", "01110", "00001", "00001", "11110"],
    "-": ["00000", "00000", "00000", "11111", "00000", "00000", "00000"],
    " ": ["00000"] * 7,
}


class Canvas:
    def __init__(self, w, h, bg):
        self.w, self.h = w, h
        self.px = [bytearray([bg]) * w for _ in range(h)]

    def rect(self, x0, y0, x1, y1, c):
        for y in range(max(0, y0), min(self.h, y1)):
            row = self.px[y]
            row[max(0, x0):min(self.w, x1)] = bytes([c]) * (min(self.w, x1) - max(0, x0))

    def circle(self, cx, cy, r, c, inner=0):
        for y in range(max(0, cy - r), min(self.h, cy + r + 1)):
            for x in range(max(0, cx - r), min(self.w, cx + r + 1)):
                d = (x - cx) ** 2 + (y - cy) ** 2
                if inner * inner <= d <= r * r:
                    self.px[y][x] = c

    def text(self, x, y, s, c, scale=4):
        for ch in s:
            g = FONT[ch]
            for gy, line in enumerate(g):
                for gx, bit in enumerate(line):
                    if bit == "1":
                        self.rect(x + gx * scale, y + gy * scale, x + (gx + 1) * scale, y + (gy + 1) * scale, c)
            x += 6 * scale

    def rows(self):
        return [bytes(r) for r in self.px]

# ---------------------------------------------------------------- fixtures

# palette: 0 background, 1 outline, 2 steel, 3 dark steel, 4 motor blue, 5 pipe grey,
# 6 label text, 7 base, 8 warning red, 9..40 heat gradient (orange -> red)
BASE_PALETTE = [(236, 240, 244), (40, 44, 52), (150, 160, 172), (96, 104, 116), (52, 96, 160),
                (120, 128, 136), (20, 20, 20), (70, 70, 70), (200, 30, 30)]
HEAT = [(255, 200 - i * 5, 60 - min(i, 12) * 5) for i in range(32)]


def draw_pump(variant):
    w, h = 800, 600
    pal = BASE_PALETTE + HEAT
    if variant == "denied":  # a visibly different machine: green motor, grey background
        pal[0], pal[4] = (210, 214, 210), (60, 130, 80)
    cv = Canvas(w, h, 0)
    if variant == "image":                             # overheating haze around the volute
        for i, r in enumerate(range(140, 96, -2)):
            cv.circle(530, 380, r, 9 + min(i, 31), inner=r - 2)
    cv.rect(80, 470, 720, 500, 7)                      # base plate
    cv.rect(120, 300, 380, 460, 4)                     # motor body
    for fx in range(130, 380, 22):                     # cooling fins
        cv.rect(fx, 290, fx + 10, 470, 3)
    cv.rect(380, 360, 430, 400, 3)                     # coupling
    cv.circle(530, 380, 95, 2)                         # volute casing
    cv.circle(530, 380, 95, 1, inner=90)
    cv.circle(530, 380, 30, 3)                         # impeller hub
    cv.rect(625, 360, 760, 400, 5)                     # INLET pipe (right, horizontal)
    cv.rect(740, 345, 770, 415, 3)                     # inlet flange
    cv.rect(510, 160, 550, 290, 5)                     # outlet pipe (up)
    cv.rect(495, 150, 565, 170, 3)                     # outlet flange
    if variant == "image":
        cv.text(668, 310, "INLET", 6, 4)
        cv.text(40, 40, "MF-PUMP-001", 6, 6)
        cv.text(40, 100, "SYNTHETIC", 5, 4)
        cv.rect(670, 60, 700, 140, 8)                  # thermometer
        cv.circle(685, 150, 20, 8)
    else:
        cv.text(40, 40, "MF-FILE-DENIED", 8, 6)
        cv.text(40, 100, "RESTRICTED CONTROL", 6, 4)
        cv.text(40, 140, "MF-ASSET-002", 6, 4)
    return w, h, cv.rows(), pal


def build_image(variant, logical):
    w, h, rows, pal = draw_pump(variant)
    comment = (f"Synthetic fixture {logical} generated by {GENERATOR}; CC0-1.0; "
               "no people, customer data or location metadata")
    return png_indexed(w, h, rows, pal, comment)


def build_oversize():
    """> 5 MiB PNG: deterministic SHA-256 counter-mode noise, 1400x1400 RGB (~5.6 MiB)."""
    w = h = 1400
    rows = []
    seed = b"MF-UPLOAD-INVALID oversize v1"
    ctr = 0
    for _ in range(h):
        buf = bytearray()
        while len(buf) < w * 3:
            buf += hashlib.sha256(seed + ctr.to_bytes(8, "big")).digest()
            ctr += 1
        rows.append(bytes(buf[:w * 3]))
    return png_rgb(w, h, rows, "Synthetic fixture MF-UPLOAD-INVALID (oversize image) generated by "
                   f"{GENERATOR}; CC0-1.0; random noise, no people or location metadata")


INVALID_TXT = (
    "MF-UPLOAD-INVALID (text part)\n"
    "Synthetic SMF PoC fixture. This plain-text file must be rejected by the PoC's image-only\n"
    "upload control (SMF-10 FILE-03). It contains no customer or personal data.\n"
    f"Generated by {GENERATOR}; licence CC0-1.0.\n"
).encode("ascii")

FIXTURES = [
    # logical id, relative path (to repo root), builder, committed?, purpose
    ("MF-IMAGE-001", "testing/fixtures/files/MF-IMAGE-001.png", lambda: build_image("image", "MF-IMAGE-001"), True,
     "Synthetic equipment image linked to MF-CASE-001 (contract: PNG/JPEG <= 2 MiB)"),
    ("MF-FILE-DENIED", "testing/fixtures/files/MF-FILE-DENIED.png", lambda: build_image("denied", "MF-FILE-DENIED"), True,
     "Separate image linked only to MF-CASE-002, no public link"),
    ("MF-UPLOAD-INVALID", "testing/fixtures/files/MF-UPLOAD-INVALID.txt", lambda: INVALID_TXT, True,
     "Non-image (.txt) part of MF-UPLOAD-INVALID"),
    ("MF-UPLOAD-INVALID", "testing/fixtures/generated/MF-UPLOAD-INVALID-oversize.png", build_oversize, False,
     "> 5 MiB image part of MF-UPLOAD-INVALID; regenerated, not committed"),
]
LIMITS = {"MF-IMAGE-001": ("max", 2 * MIB), "MF-FILE-DENIED": ("max", 2 * MIB)}


def entry(lid, rel, data, committed, purpose):
    e = {"logical_id": lid, "path": rel, "bytes": len(data), "sha256": hashlib.sha256(data).hexdigest(),
         "md5": hashlib.md5(data).hexdigest(), "media_type": "text/plain" if rel.endswith(".txt") else "image/png",
         "committed": committed, "purpose": purpose, "generator": GENERATOR, "licence": LICENCE}
    if rel.endswith(".png"):
        e["png_size"] = list(struct.unpack(">II", data[16:24]))
    return e


def check_limits(e):
    errs = []
    if e["logical_id"] in LIMITS and e["bytes"] > LIMITS[e["logical_id"]][1]:
        errs.append(f"{e['path']}: {e['bytes']} bytes exceeds 2 MiB")
    if e["path"].endswith("oversize.png") and e["bytes"] <= 5 * MIB:
        errs.append(f"{e['path']}: {e['bytes']} bytes is not > 5 MiB")
    return errs


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="verify only; regenerate nothing")
    a = ap.parse_args()
    errors, entries = [], []
    for lid, rel, build, committed, purpose in FIXTURES:
        data = build()
        e = entry(lid, rel, data, committed, purpose)
        entries.append(e)
        errors += check_limits(e)
        p = ROOT / rel
        if a.check:
            if committed and (not p.exists() or p.read_bytes() != data):
                errors.append(f"{rel}: committed file differs from generator output")
        else:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_bytes(data)
    manifest = {
        "manifest_version": "1.0.0",
        "fixture_version": "v1",
        "story": "SMF-3",
        "note": ("Local file fixtures for MF-IMAGE-001, MF-FILE-DENIED and MF-UPLOAD-INVALID. md5 is "
                 "listed because Salesforce ContentVersion.Checksum is the file's MD5, so the seed can "
                 "verify uploaded bytes; sha256 is the fixture hash for evidence. Regenerate with "
                 f"`python3 {GENERATOR}`; verify with `--check`."),
        "fixtures": entries,
    }
    text = json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"
    if a.check:
        if not MANIFEST.exists() or MANIFEST.read_text(encoding="utf-8") != text:
            errors.append("testing/fixtures/manifest.json differs from generator output")
    else:
        MANIFEST.write_text(text, encoding="utf-8", newline="\n")
    if errors:
        print("FAIL\n - " + "\n - ".join(errors))
        return 1
    for e in entries:
        print(f"OK {e['logical_id']:<18} {e['bytes']:>8} B  sha256:{e['sha256'][:16]}…  {e['path']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
